var wordCard = [
  ['ball', 'fingerprint', 'recycle', 'tug boat', 'studio'],
  ['The Rolling Stones', 'silence', 'barber', 'bugle', 'concert'],
  ['chalk', 'snooze', 'random', 'glove compartment', 'paint'],
  ['homework', 'dip', 'definition', 'mallet', 'call'],
  ['George Steinbrenner', 'waves', 'coffee bean', 'lot', 'Michael Jackson'],
  ['decoration', 'back pack', 'sphere', 'nuclear power', 'lobster'],
  ['Frankenstein', 'diplomat', 'wool', 'Brooklyn', 'pipe'],
  ['university', 'accordian', 'baloney', 'real estate', 'indegestion'],
  ['soup', 'ice', 'dancing', 'aircraft', 'cricket'],
  ['Keith Richards', 'hymn', 'hypnosis', 'venom', 'Demi Moore'],
  ['Stephen King', 'stock market', 'smile', 'condominium', 'gopher'],
  ['hard', 'breeze', 'tutor', 'journey', 'frost'],
  ['pogo stick', 'prison cell', 'boredom', 'link', 'chlorine'],
  ['wacky', 'pop', 'tree fort', 'general', 'pizza'],
  ['moat', 'altar', 'nose', 'harpoon', 'wheelbarrow'],
  ['dangle', 'heaven', 'confidence', 'launch', 'frying-pan'],
  ['taxi', 'spill', 'huddle', 'thirst', 'perfect'],
  ['bite', 'gripe', 'flashback', 'technology', 'cattle'],
  ['right', 'lice', 'italian food', 'erupt', 'taste'],
  ['water', 'post', 'skirt', 'boulevard', 'swine'],
  ['scoop', 'Robert Deniro', 'bronco', 'complain', 'haunt'],
  ['land', 'grease', 'bathroom', 'fight', 'hang up'],
  ['Pennsylvania', 'hog', 'mouth', 'channel', 'salon'],
  ['problem', 'dare', 'oral', 'Transylvania', 'name'],
  ['help', 'zero', 'foot', 'superior', 'dolly'],
  ['Tennesse', 'wardrobe', 'nip', 'sir', 'hood'],
  ['roast', 'words', 'sexy', 'water gun', 'stack'],
  ['locker', 'antler', 'mosque', 'take-out', 'canvas'],
  ['saliva', 'purell', 'cantaloupe', 'tour', 'calorie'],
  ['shorts', 'pipe', 'floor', 'windows', 'stamp'],
  ['speed', 'chips', 'fat', 'host', 'knee'],
  ['crash', 'fold', 'stray', 'make out', 'peg'],
  ['backyard', 'quartet', 'wedge', 'lock', 'broker'],
  ['sign language', 'Audi', 'pink eye', 'Spike Lee', 'mint']
];
